sudo: false

cache:
  directories:
    - tests/elm-stuff/build-artifacts

env:
  matrix:
    - ELM_VERSION=0.18.0 TARGET_NODE_VERSION=node

install:
  - nvm install $TARGET_NODE_VERSION
  - nvm use $TARGET_NODE_VERSION
  - node --version
  - npm --version
  - npm install -g elm-use elm-test elm-format
  - elm-use $ELM_VERSION
  - npm install
  - travis_retry elm-package install --yes
  - cd tests
  - travis_retry elm-package install --yes
  - cd ..

script:
  - elm-format --validate src tests
  - npm test
